### ISSUE TITLE
Syntax-Highlight Color for "Invalid" Things Could Be More Legible

### ISSUE THREAD

**Issue by rbrooks** [atom/base16-tomorrow-dark-theme#10]
This theme is absolutely **GREAT**!  But the Syntax-Highlight color for "Invalid" elements has a red background that makes things very difficult to read, particularly JSON comments. This is what I'm referring to:

```
.invalid.illegal {
  background-color: #cc6666;
  color: #1d1f21;
}
```

Bring up any JSON file with lots of code comments. You will see what I mean.

I realize that Code Comments are not in the JSON spec, but that **are** a proposed addition to the spec.

The default "Atom Dark" Syntax theme has better-looking "Invalid" elements. They are a shade of purple, and they subdue the background, so it's more pleasant on the eye.  I recommend a similar approach... something like this:

```
.invalid.illegal {
  background-color: #330000;
  color: #990000;
}
```

**Comment by simurai** [comment]
Gonna close this as `wontfix`, see this comment for the reasoning: https://github.com/atom/base16-tomorrow-dark-theme/pull/22#issuecomment-138168945
