### ISSUE TITLE
Bracket matching disappears with Shadow DOM

### ISSUE THREAD

**Issue by fungilation** [atom/base16-tomorrow-dark-theme#11]
Bracket Matcher package works with keyboard controls. Matched brackets just doesn't underline when Shadow DOM setting is on, which is now default since Atom 0.166

Also using Seti UI theme

**Comment by nathansobo** [comment]
This should be fixed in the next release by a correction to the default styling of the bracket matcher in https://github.com/atom/bracket-matcher/commit/069a47c49123bdf68c278667803555146a10ca7c.
