### ISSUE TITLE
Cursor is invisible when it's in the line length ruler position

### ISSUE THREAD

**Issue by xeron** [atom/base16-tomorrow-dark-theme#16]
Screenshot attached. Red circle indicated current cursor position. Same issue with Tomorrow Light theme.
No such issue with Atom or One themes.

![screen shot 2015-06-09 at 2 19 43 pm](https://cloud.githubusercontent.com/assets/110569/8070016/3cbef6d8-0eb3-11e5-9f6e-09ba78e698ca.png)

**Comment by lordjavac** [comment]
I'm also having this issue. Theme version 0.27.0, running in Atom 1.0.9 on Windows 10 and also on Mac OS X 10.10 (Yosemite).

**Comment by izuzak** [comment]
Seeing this as well. /cc @simurai and @as-cii who enjoy reading about these kinds of issues :trollface:

**Comment by simurai** [comment]
> who enjoy reading about these kinds of issues

:stuck_out_tongue:

This got fixed in https://github.com/atom/wrap-guide/pull/36. But I forgot to publish a new version, sorry. Will be in the next Atom update.

**Comment by mikebronner** [comment]
This issue appears to have resurfaced. Is there a work-around we can put in our styles.less?
