### ISSUE TITLE
please offer an option without the underlines

### ISSUE THREAD

**Issue by wolftune** [atom/base16-tomorrow-dark-theme#19]

**Comment by simurai** [comment]
You could remove them described here: https://github.com/atom/base16-tomorrow-dark-theme/issues/18#issuecomment-135944308

Although I wonder if the original theme has underlines too? I think not. Also the TM version doesn't: https://tmtheme-editor.herokuapp.com/#!/editor/theme/Base16%20Tomorrow%20Dark

And not sure if there was a specific reason to have them in Atom's port: https://github.com/atom/base16-tomorrow-dark-theme/commit/5c56e19c5a43c5d6014d558a372097d5dfdc28e2#commitcomment-8530801 /cc @wfarr do you still remember? Maybe to differentiate tags/classes a bit more?

**Comment by wolftune** [comment]
Thanks, I manually removed them, much nicer. I won't feel bad if you close this ticket, up to you

**Comment by izuzak** [comment]
I'd be :+1: on removing the underlines if the original theme doesn't have them (and it does look like it doesn't).
