### ISSUE TITLE
Most code in c-sharp is yellow

### ISSUE THREAD

**Issue by forivall** [atom/base16-tomorrow-dark-theme#27]
![screen shot 2016-04-14 at 2 12 06 pm](https://cloud.githubusercontent.com/assets/760204/14543828/f19b2050-024a-11e6-8367-406f8c79d9b4.png)
and for comparison, with atom-dark
![screen shot 2016-04-14 at 2 13 40 pm](https://cloud.githubusercontent.com/assets/760204/14543892/25be63ba-024b-11e6-9279-023aa77d3473.png)

The light variant also has this issue.

**Comment by simurai** [comment]
This issue seems to be improved with https://github.com/atom/base16-tomorrow-dark-theme/pull/30
